version: '3.5'

services: 
  server: 
    container_name: proxy-server
    build: ./server
    volumes: 
      - ./server:/home/node/server
    ports: 
      - '3000:3000' 
    env_file:
      - .env
    depends_on:
      - redis

  redis: 
    image: 'redis:alpine'